name: neumorphic_clock
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  analog_clock: ^0.1.1
  google_nav_bar: ^5.0.7
  flutter_bloc: ^9.1.1   #^8.1.3
  sqflite: ^2.4.2
  flutter_neumorphic_plus: ^3.4.0
  path_provider: ^2.1.5
  alarm: ^5.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/audio/